### ISSUE TITLE
As a user, I should be able to see all my appointments

### ISSUE THREAD

**Issue by shreyas2499** [gcivil-nyu-org/INT2-Monday-Spring2024-Team-1#19]
**User Stories**
As a user, I would like to see a tab which has all my appointments with hospitals. It should have a complete history of all my past appointments along with the Dates of those appointments, the hospital names where the appointment took place and also the Doctor's name with whom the appointment was done. 

**Acceptance Criteria**
I should be able to see a tab through which I can find information about all my past medical appointments. 

**Definition of Done**
This user story will be done, once the above feature has been implemented, tested and the coverage satisfies the minimum required benchmark.

PS: The wireframe for the above will be added to the PBI later

**Comment by gamSeier** [comment]
Will be captured by filtering ability.
