### ISSUE TITLE
Doctor account - Generate reports

### ISSUE THREAD

**Issue by samkitshah18** [gcivil-nyu-org/INT2-Monday-Spring2024-Team-1#196]
If no reports are selected, generate report button appears when clicked throws server error:
![image](https://github.com/gcivil-nyu-org/INT2-Monday-Spring2024-Team-1/assets/61347723/7ddcaf8f-01d1-4307-bd6a-9e94caa754e8)
![image](https://github.com/gcivil-nyu-org/INT2-Monday-Spring2024-Team-1/assets/61347723/aef2c640-eebd-4c50-b350-b09a92beac58)

**Comment by shreyas2499** [comment]
RCA:
The page shouldn't have been visible to doctors in the first place. Add the required checks for that. And the Generate button was failing because one of the fields was not being sent. Updated that
