### ISSUE TITLE
Enter invalid url

### ISSUE THREAD

**Issue by samkitshah18** [gcivil-nyu-org/INT2-Monday-Spring2024-Team-1#198]
Even though the navbar doesnt have any hyperlink but when logged in as a doctor/Admin entering the url: http://health-env4.eba-sjmgxapv.us-west-2.elasticbeanstalk.com/hs/viewRequests brings up a (Your Requests) page. In reality this url should only work for the patient login.

**Comment by shreyas2499** [comment]
RCA:
Permissions had to be set
