### ISSUE TITLE
Copying the ‘Requests’ url into a non-logged in screen results in a ‘not found’ error.

### ISSUE THREAD

**Issue by siddharthcv77** [gcivil-nyu-org/INT2-Monday-Spring2024-Team-1#202]
https://github.com/gcivil-nyu-org/INT2-Monday-Spring2024-Team-1/assets/144621775/69c82b3f-1ed1-4a03-a853-b06556b8c541

**Comment by shreyas2499** [comment]
RCA: Permissions were not set
