### ISSUE TITLE
Chat 1-1 (bug fix for img and click trigger more message display issue, notification)

### ISSUE THREAD

**Issue by bonnieee702** [gcivil-nyu-org/INT2-Monday-Spring2024-Team-1#207]

**Comment by shreyas2499** [comment]
@bonnieee702, we currently do not have the chat 1-1 feature implemented. Could you please tell us a little more about the issue you are facing?

**Comment by bonnieee702** [comment]
omg, sorry i was adding user story for our team board this sprint, maybe
there was issue when i creating it, please ignore and close it.
